Blog_home:
    pattern: /
    defaults: { _controller: BlogBundle:Public:index }

Blog_page:
    pattern: /page/{page}
    defaults: { _controller: BlogBundle:Public:page }
    requirements:
        page: \d+

Blog_article:
    pattern: /article/{_locale}/{annee}/{slug}.{_format}
    defaults: { _controller: BlogBundle:Public:article, format: html, _locale: fr }
    requirements:
        annee: \d{4}
        _format: rss|html
        _locale: fr|en
