Blog_home:
    pattern: /
    defaults: { _controller: BlogBundle:Public:index }

Blog_page:
    pattern: /page/{page}
    defaults: { _controller: BlogBundle:Public:page }
    requirements:
        page: \d+

Blog_article:
    pattern: /article/{slug}.{_format}
    defaults: { _controller: BlogBundle:Public:article, _format: html }
    requirements:
        _format: html
